# Generated by Django 5.0.6 on 2024-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('mu', 'mens upper wear'), ('mb', 'mens bottom wear'), ('wu', 'Womens upper wear'), ('wb', 'Womens bottom wear')], max_length=3)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'Large'), ('xl', 'Extra large'), ('xxl', 'Double extra large')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
