# Generated by Django 5.0.6 on 2024-05-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melodyapp', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
